### ISSUE TITLE
Most Stable Windows Release

### ISSUE THREAD

**Issue by MOHAND99** [spring-projects-experimental/spring-boot-migrator#1045]
**Describe the bug**
I tried using version 0.15.0, but I encountered the same issue mentioned in #1035. So, I downgraded to version 0.14.0 as recommended in #1035, which resolved that error. However, I am now experiencing a different error. Could you please let me know the most stable release for Windows?

**SBM Version**
0.14.0

**SBM Application**
spring-boot-migrator

**To Reproduce**
1. java -jar spring-boot-migrator.jar
2. scan application-path

**Stacktrace**
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "org.springframework.sbm.build.api.Dependency.getVersion()" is null
        at org.springframework.sbm.boot.common.conditions.HasSpringBootDependencyImport.resolveCoordinates(HasSpringBootDependencyImport.java:56)
        at org.springframework.sbm.boot.common.conditions.HasSpringBootDependencyImport.lambda$hasBuildFileDependencyImport$0(HasSpringBootDependencyImport.java:49)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
        at org.springframework.sbm.boot.common.conditions.HasSpringBootDependencyImport.hasBuildFileDependencyImport(HasSpringBootDependencyImport.java:50)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
        at org.springframework.sbm.boot.common.conditions.HasSpringBootDependencyImport.evaluate(HasSpringBootDependencyImport.java:44)

**Desktop :**
 - OS: Windows
 - Version: 11

**Comment by MOHAND99** [comment]
For me I used STS support by clicking right click on an opened maven project ![image](https://github.com/user-attachments/assets/7048b6f3-5f77-4e51-86bb-a8f2f9b3836d) 
then I clicked on `Upgrade Spring Boot Version...`, selecting all versions 
![image](https://github.com/user-attachments/assets/f1629d90-7ffe-4d38-9c06-228ce9198174)
