### ISSUE TITLE
`NullPointerException` from `NoRepositoryExistsCondition`

### ISSUE THREAD

**Issue by odrotbohm** [spring-projects-experimental/spring-boot-migrator#179]
I'm trying the Boot 3 migration prototype in the `143-implement-recipe-boot-27-30-dependency-version-update` branch. When building that branch, running SBM, and scanning the `server` project in [Spring RESTBucks](https://github.com/odrotbohm/spring-restbucks), I run into this:

```
java.lang.NullPointerException
	at org.springframework.sbm.build.migration.conditions.NoRepositoryExistsCondition.lambda$evaluate$0(NoRepositoryExistsCondition.java:21)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538)
	at org.springframework.sbm.build.migration.conditions.NoRepositoryExistsCondition.evaluate(NoRepositoryExistsCondition.java:21)
	at org.springframework.sbm.engine.recipe.Action.isApplicable(Action.java:51)
	at org.springframework.sbm.engine.recipe.Recipe.lambda$isApplicable$0(Recipe.java:91)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at org.springframework.sbm.engine.recipe.Recipe.isApplicable(Recipe.java:91)
	…
```

The relevant code

```java
@Override
public boolean evaluate(ProjectContext context) {
    return context.getBuildFile().getRepositories().stream()
            .noneMatch(r -> r.getId().equals(id) || r.getUrl().equals(url));
}
```

would indeed fail if either no `<id>` or `<url>` would be defined but in the scanned project, [that's not the case](https://github.com/odrotbohm/spring-restbucks/blob/6a9364af69d61c56d414a85ff578eb65f18094ed/server/pom.xml#L316-L362). 🤔

**Comment by fabapp2** [comment]
Thanks @odrotbohm!
Took me a moment to get back to this.
Indeed, The condition needs more love...
