### ISSUE TITLE
Nullpointer during scaning

### ISSUE THREAD

**Issue by kgonia** [spring-projects-experimental/spring-boot-migrator#467]
I got Nullpointer during scan

**Stacktrace**
````
[ok] Found pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'true', changes will be committed to branch [main] after each recipe.
 [!] Java 11 or 17 is required. Check found Java 18.
[ok] Found required source dir 'src/main/java'.


Maven        100% │███████████████████████████│ 2/2 (0:00:13 / 0:00:00) 
22:28:18.381 [main] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!
org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
	at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
	at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
	at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:279)
	at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:163)
	at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:54)
	at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
	at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
	at org.springframework.shell.Shell.evaluate(Shell.java:208)
	at org.springframework.shell.Shell.run(Shell.java:140)
	at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5357)
	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5210)
	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5155)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
	... 29 common frames omitted
Index: 0
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
````

**Desktop (please complete the following information):**
 - macOS
 - maven: 3.6.3
- Java 18

**Comment by fabapp2** [comment]
Hi @kgonia 
Thanks for reporting! 
Could you do us a favor and try again with JDK 17?
OpenRewrite uses JDK internals and JDK 18 is not supported.

**Comment by fabapp2** [comment]
Close this now but added #485 to improve the precondition check.
