### ISSUE TITLE
`MuleToJavaDSLDwlTransformTest` throws exception

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#484]
labels: ["type: bug","in: mule-3.9"]

**Describe the bug**

**Stacktrace**
````
[INFO] Running org.springframework.sbm.mule.actions.MuleToJavaDSLDwlTransformTest
10:00:17.413 [ForkJoinPool-1-worker-1] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!
org.openrewrite.UncaughtVisitorException: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JRightPadded.getElement()" because "l" is null
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:253)
        at org.openrewrite.java.format.BlankLinesVisitor.visit(BlankLinesVisitor.java:299)
        at org.openrewrite.java.format.BlankLinesVisitor.visit(BlankLinesVisitor.java:30)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
        at org.openrewrite.java.format.AutoFormatVisitor.visit(AutoFormatVisitor.java:56)
        at org.openrewrite.java.JavaVisitor.autoFormat(JavaVisitor.java:92)
        at org.openrewrite.java.JavaVisitor.autoFormat(JavaVisitor.java:87)
        at org.openrewrite.java.JavaTemplate$2.lambda$visitBlock$0(JavaTemplate.java:145)
        at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
        at org.openrewrite.java.JavaTemplate$2.visitBlock(JavaTemplate.java:145)
        at org.openrewrite.java.JavaTemplate$2.visitBlock(JavaTemplate.java:102)
        at org.openrewrite.java.tree.J$Block.acceptJava(J.java:745)
        at org.openrewrite.java.tree.J.accept(J.java:60)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
        at org.openrewrite.java.JavaVisitor.visitClassDeclaration(JavaVisitor.java:447)
        at org.openrewrite.java.JavaTemplate$2.visitClassDeclaration(JavaTemplate.java:264)
        at org.openrewrite.java.JavaTemplate$2.visitClassDeclaration(JavaTemplate.java:102)
        at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1069)
        at org.openrewrite.java.tree.J.accept(J.java:60)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:145)
        at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:520)
        at org.openrewrite.java.JavaTemplate.withTemplate(JavaTemplate.java:42)
        at org.openrewrite.java.tree.J.withTemplate(J.java:87)
        at org.springframework.sbm.java.impl.OpenRewriteType$1.visitClassDeclaration(OpenRewriteType.java:170)
        at org.springframework.sbm.java.impl.OpenRewriteType$1.visitClassDeclaration(OpenRewriteType.java:156)
        at org.openrewrite.java.tree.J$ClassDeclaration.acceptJava(J.java:1069)
        at org.openrewrite.java.tree.J.accept(J.java:60)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        at org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
        at org.openrewrite.java.JavaVisitor.lambda$visitCompilationUnit$10(JavaVisitor.java:466)
        at org.openrewrite.internal.ListUtils.lambda$map$0(ListUtils.java:141)
        at org.openrewrite.internal.ListUtils.map(ListUtils.java:123)
        at org.openrewrite.internal.ListUtils.map(ListUtils.java:141)
        at org.openrewrite.java.JavaVisitor.visitCompilationUnit(JavaVisitor.java:466)
        at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:119)
        at org.openrewrite.java.JavaIsoVisitor.visitCompilationUnit(JavaIsoVisitor.java:31)
        at org.openrewrite.java.JavaVisitor.visitJavaSourceFile(JavaVisitor.java:454)
        at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:39)
        at org.openrewrite.java.JavaIsoVisitor.visitJavaSourceFile(JavaIsoVisitor.java:31)
        at org.openrewrite.java.tree.J$CompilationUnit.acceptJava(J.java:1351)
        at org.openrewrite.java.tree.J.accept(J.java:60)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        at org.openrewrite.RecipeScheduler.lambda$scheduleVisit$5(RecipeScheduler.java:241)
        at org.openrewrite.RecipeScheduler.lambda$mapAsync$0(RecipeScheduler.java:49)
        at org.openrewrite.scheduling.ForkJoinScheduler.lambda$schedule$0(ForkJoinScheduler.java:41)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.JRightPadded.getElement()" because "l" is null
        at org.openrewrite.java.tree.JRightPadded.getElements(JRightPadded.java:102)
        at org.openrewrite.java.tree.J$Block.getStatements(J.java:732)
        at org.openrewrite.java.format.BlankLinesVisitor.visitMethodDeclaration(BlankLinesVisitor.java:149)
        at org.openrewrite.java.format.BlankLinesVisitor.visitMethodDeclaration(BlankLinesVisitor.java:30)
        at org.openrewrite.java.tree.J$MethodDeclaration.acceptJava(J.java:3221)
        at org.openrewrite.java.tree.J.accept(J.java:60)
        at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
        ... 52 common frames omitted

````

**Comment by sanagaraj-pivotal** [comment]
@fabapp2 I think the implementation of Triggermesh is flawed, the reason we are seeing an exception is because the xml supplied in the test is not valid, 


The test that is causing the exception is this: `MuleToJavaDSLDwlTransformTest.multipleDWLTransformInSameFlowShouldProduceMultipleClassesWithTriggerMeshEnabled`

The exception is due to the fact that the input xml supplied is invalid, there is no input and corresponding output mentioned in xml for a channel adapter hence the exception.

I supplied a simple input xml with transformation for to test with trigger mesh, following were the results:

Input: 
```xml
<?xml version="1.0" encoding="UTF-8"?>

            <mule xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw" xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
                xmlns:spring="http://www.springframework.org/schema/beans"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
            http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
            http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
            http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd">
                <flow name="dwlFlow">
                    <http:listener config-ref="HTTP_Listener_Configuration" path="/dwl" doc:name="HTTP"/>
               
                    <logger message="payload to be sent: #[new String(payload)]" level="INFO" doc:name="Log the message content to be sent"/>
                   
                    <dw:transform-message doc:name="action transform">
                        <dw:set-payload><![CDATA[%dw 1.0
            %output application/json
            ---
            {
                action_Code: 10,
                returnCode:  20
            }]]></dw:set-payload>
                    </dw:transform-message>
                   
                     <logger message="payload to be sent: #[new String(payload)]" level="INFO" doc:name="Log the message content to be sent"/>
                </flow>
            </mule>
```

output: 

```java
package com.example.javadsl;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.integration.dsl.IntegrationFlow;
import org.springframework.integration.dsl.IntegrationFlows;
import org.springframework.integration.handler.LoggingHandler;
import org.springframework.integration.http.dsl.Http;

@Configuration
public class FlowConfigurations {
    @Bean
    IntegrationFlow dwlFlow() {
        return IntegrationFlows.from(Http.inboundChannelAdapter("/dwl")).handle((p, h) -> p)
                .log(LoggingHandler.Level.INFO, "payload to be sent: #[new String(payload)]")
                .handle((p, h) -> {
                    TmDwPayload dwPayload = new TmDwPayload();
                    String contentType = "application/json";
                    if (h.get("contentType") != null) {
                        contentType = h.get("contentType").toString();
                    }
                    dwPayload.setId(h.getId().toString());
                    dwPayload.setSourceType(contentType);
                    dwPayload.setSource(h.get("http_requestUrl").toString());
                    dwPayload.setPayload(p.toString());
                    return dwPayload;
                })
                .transform(DwlFlowTransformTM_2::transform)
                .log(LoggingHandler.Level.INFO, "payload to be sent: #[new String(payload)]")
                .get();
    }
}
```

```java
package com.example.javadsl;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class DwlFlowTransformTM_2 {
    public static class DataWeavePayload {
        public String input_data;
        public String spell;
        public String input_content_type;
        public String output_content_type;
    };

    public static String transform(TmDwPayload payload) {
        String uuid = payload.getId();
        String url = System.getenv("K_SINK");
        HttpClient client = HttpClient.newHttpClient();
        HttpRequest.Builder requestBuilder;
        DataWeavePayload dwPayload = new DataWeavePayload();

        if (payload.getSourceType().contains(";")) {
            dwPayload.input_content_type = payload.getSourceType().split(";")[0];
        } else {
            dwPayload.input_content_type = payload.getSourceType();
        }
        dwPayload.output_content_type = "application/json";

        //TODO: Verify the spell conforms to Dataweave 2.x: https://docs.mulesoft.com/mule-runtime/4.4/migration-dataweave
        dwPayload.spell = "%dw 1.0\n%output application/json\n---\n{\n    action_Code: 10,\n    returnCode:  20\n}";
        dwPayload.input_data = payload.getPayload();
        String body;

        try {
            requestBuilder = HttpRequest.newBuilder(new URI(url));
            ObjectMapper om = new ObjectMapper();
            body = om.writeValueAsString(dwPayload);
        } catch (Exception e) {
            System.out.println("Error sending request: " + e.toString());
            return null;
        }

        requestBuilder.setHeader("content-type", "application/json");
        requestBuilder.setHeader("ce-specversion", "1.0");
        requestBuilder.setHeader("ce-source", payload.getSource());
        requestBuilder.setHeader("ce-type", "io.triggermesh.dataweave.transform");
        requestBuilder.setHeader("ce-id", payload.getId());

        HttpRequest request = requestBuilder.POST(HttpRequest.BodyPublishers.ofString(body)).build();

        try {
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            // TODO: verify the response status and body
            return response.body();
        } catch (Exception e) {
            System.out.println("Error sending event: " + e.toString());
            return null;
        }
    }
}

```

I was under the impression trigger mesh will package the DWL payload into an http request and a service translates it, if we see the generated classes above, the dwl content is not sent into http request at all:
```xml
          <dw:set-payload><![CDATA[%dw 1.0
            %output application/json
            ---
            {
                action_Code: 10,
                returnCode:  20
            }]]></dw:set-payload>
```
