### ISSUE TITLE
MigrateXmlToJavaConfigurationAction:Cannot invoke "java.nio.file.Path.toFile()" because "path" is null

### ISSUE THREAD

**Issue by liyunde** [spring-projects-experimental/spring-boot-migrator#494]
**Describe the bug**
 Action [MigrateXmlToJavaConfigurationAction] 'Migrate xml bean configuration to Java bean configuration.' failed: Cannot invoke "java.nio.file.Path.toFile()" because "path" is null

**To Reproduce**
1. a initialize-spring-boot-migration 
2. a migrate-spring-xml-to-java-config
3. stacktrace

**Expected behavior**

Applying recipe 'migrate-spring-xml-to-java-config'
 [X] Migrate xml bean configuration to Java bean configuration.
Action [MigrateXmlToJavaConfigurationAction] 'Migrate xml bean configuration to Java bean configuration.' failed: Cannot invoke "java.nio.file.Path.toFile()" because "path" is null
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
usercenter-migration:> stacktrace

**Stacktrace**
org.springframework.sbm.engine.recipe.ActionFailedException: Action [MigrateXmlToJavaConfigurationAction] 'Migrate xml bean configuration to Java bean configuration.' failed: Cannot invoke "java.nio.file.Path.toFile()" because "path" is null
        at org.springframework.sbm.engine.recipe.Action.applyWithStatusEvent(Action.java:43)
        at org.springframework.sbm.engine.recipe.Recipe.apply(Recipe.java:101)
        at org.springframework.sbm.engine.commands.ApplyCommand.execute(ApplyCommand.java:61)
        at org.springframework.sbm.shell.ApplyShellCommand.apply(ApplyShellCommand.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
        at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
        at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
        at org.springframework.shell.Shell.evaluate(Shell.java:208)

**Additional context**
spring4.3 xml config web project
mybatis-spring:1.3
spring-jdbc
spring-web
lombok
guava

xml:
<context:component-scan
<tx:annotation-driven
<aop:config>
<beans profile=
<bean id=

**Comment by fabapp2** [comment]
HI @liyunde 

Thank you for reporting this 🚀 
...and sorry for my late reply, I was on vacation.

The whole XML to JavaConfig stuff is very(!) experimental and incomplete.
It is the result of a spike and since I coded this (let's say hacked, I remember the code to be quite ugly) nothing happened.
It is technically possible to migrate XML to Java bean configuration but would need much more love to be of use for any non-example application.
The code was good enough to migrate an example application but problems for all other cases are expected.
I am afraid it is currently out of scope as we are focusing on Spring Boot 3 upgrades which take up all our time.

But, If you want to look into this and provide a PR, I am more than happy to assist you?

**Comment by fabapp2** [comment]
Closing as this functionality is out of scope for now. Feel free to reopen in case you want to look into this and contribute.
