### ISSUE TITLE
IndexOutOfBoundsException: Illegal start index

### ISSUE THREAD

**Issue by 10142327** [spring-projects-experimental/spring-boot-migrator#694]
**Describe the bug**
Errors during migration

**To Reproduce**
1. java -jar spring-boot-migrator.jar
2. scan <path to application>

**Stacktrace**

`
[ok] Found pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'true', changes will be committed to branch [migration-auto] after each recipe.
[ok] Required Java version (17) was found.
[ok] Found required source dir 'src/main/java'.

Maven        100% │████████████████████████████████│ 20/20 (0:00:13 / 0:00:00)
14:08:39.661 [main] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!
java.lang.IndexOutOfBoundsException: Illegal start index
        at java.base/java.util.regex.Matcher.find(Matcher.java:770)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.lambda$visitVariables$28(ReloadableJava17ParserVisitor.java:1391)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariables(ReloadableJava17ParserVisitor.java:1398)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:1346)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitVariable(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:1045)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1511)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1620)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertStatements(ReloadableJava17ParserVisitor.java:1602)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitClass(ReloadableJava17ParserVisitor.java:472)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitClass(ReloadableJava17ParserVisitor.java:71)        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convert(ReloadableJava17ParserVisitor.java:1482)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.convertAll(ReloadableJava17ParserVisitor.java:1535)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:518)
        at org.openrewrite.java.isolated.ReloadableJava17ParserVisitor.visitCompilationUnit(ReloadableJava17ParserVisitor.java:71)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.lambda$parseInputs$0(ReloadableJava17Parser.java:178)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:200)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:217)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:118)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
        at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
        at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
        at org.springframework.shell.Shell.evaluate(Shell.java:208)
        at org.springframework.shell.Shell.run(Shell.java:140)
        at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
        at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
14:08:39.669 [main] ERROR o.s.s.o.RewriteExecutionContext - Exception occured!

`

**Desktop:**
 - OS: Windows
 - Version 11

**Additional context**
The Spring Boot project has multiple modules

**Comment by fabapp2** [comment]
Hi @10142327,
thanks for reporting 🚀 

The provided stacktrace indicates that some Java class can't be parsed by underlying OpenRewrite.
We are in the middle of an upgrade to the latest OpenRewrite (7.34.3) while the current SBM is still on 7.29.0 so maybe this is working after the version upgrade.
Without access to the problematic project/class I can't investigate the error and without changes to OpenRewrite can't provide additional information to the exception message either, sorry.

The best help I can provide is to ask you to configure [OpenRewrite's Maven Plugin](https://docs.openrewrite.org/running-recipes/getting-started#step-2-add-rewrite-maven-plugin-or-rewrite-gradle-plugin-to-your-project) and see if scanning works then and if not to add an issue to their [repo](https://github.com/openrewrite/rewrite).
Please let me know about your learnings in case you give this a try. 🙏

**Comment by vkolodrevskiy** [comment]
I observe similar issues, for me it seems it's due to new keywords like: **record**, **sealed** etc.
Is there a way to pass java syntax version?

**Comment by fabapp2** [comment]
Hi @vkolodrevskiy,
the java version is retrieved from env `java.version` by OpenRewrite when the JavaParser gets constructed.

I tested parsing a record with Rewrite 7.29.0 which is currently used in SBM and it fails as you observed. 
With OpenRewrite 7.34.3 a record gets successfully parsed. I am working on the upgrade to latest rewrite version and will close this issue hoping this problem is solved then.
