### ISSUE TITLE
Tests failing to run on Ubuntu 22

### ISSUE THREAD

**Issue by abalzan** [spring-projects-experimental/spring-boot-migrator#703]
**Describe the bug**
Failing to run the tests on Ubuntu, 
```
-------------------------------------------------------------------------------
Test set: org.springframework.sbm.project.buildfile.OpenRewriteMavenBuildFileTest
-------------------------------------------------------------------------------
Tests run: 42, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.799 s <<< FAILURE! - in org.springframework.sbm.project.buildfile.OpenRewriteMavenBuildFileTest
getEffectiveDependencies  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size: 3 but was: 2 in:
[<dependency>
   <groupId>javax.annotation</groupId>
   <artifactId>javax.annotation-api</artifactId>
   <version>1.3.2</version>
   <type>jar</type>
   <scope>test</scope>
</dependency>,
    <dependency>
   <groupId>com.example</groupId>
   <artifactId>module2</artifactId>
   <version>1.0</version>
   <type>jar</type>
   <scope>compile</scope>
</dependency>]
	at org.springframework.sbm.project.buildfile.OpenRewriteMavenBuildFileTest$GetDependenciesMultiModuleTest.getEffectiveDependencies(OpenRewriteMavenBuildFileTest.java:1031)
```

**SBM Version**
Commit hash: a531683e042895d53d4d00bf2800a9b53a9efff2

**SBM Application**
N/A

**To Reproduce**
mvn clean install

**Expected behavior**
Tests to pass

**Screenshots**

**Stacktrace**
```
11:03:21.614 [main] WARN  o.o.j.i.ReloadableJava17Parser - /home/andrei/IdeaProjects/spring-boot-migrator/components/sbm-core/target/dummy-test-path/src/main/java/Cat.java:1: error: package javax.validation.constraints does not exist
11:03:21.614 [main] WARN  o.o.j.i.ReloadableJava17Parser - import javax.validation.constraints.Email;
11:03:21.614 [main] WARN  o.o.j.i.ReloadableJava17Parser -                                    ^
11:03:21.616 [main] WARN  o.o.j.i.ReloadableJava17Parser - /home/andrei/IdeaProjects/spring-boot-migrator/components/sbm-core/target/dummy-test-path/src/main/java/Cat.java:3: error: cannot find symbol
11:03:21.616 [main] WARN  o.o.j.i.ReloadableJava17Parser -     @Email
11:03:21.616 [main] WARN  o.o.j.i.ReloadableJava17Parser -      ^
11:03:21.616 [main] WARN  o.o.j.i.ReloadableJava17Parser -   symbol:   class Email
11:03:21.616 [main] WARN  o.o.j.i.ReloadableJava17Parser -   location: class Cat
11:03:21.797 [main] ERROR o.s.sbm.java.impl.OpenRewriteMember - Could not get Type for annotation: 'javax.validation.constraints.Email'.
[ERROR] Tests run: 42, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.696 s <<< FAILURE! - in org.springframework.sbm.project.buildfile.OpenRewriteMavenBuildFileTest
[ERROR] getEffectiveDependencies  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: 
Expected size: 3 but was: 2 in:
[<dependency>
   <groupId>javax.annotation</groupId>
   <artifactId>javax.annotation-api</artifactId>
   <version>1.3.2</version>
   <type>jar</type>
   <scope>test</scope>
</dependency>,
    <dependency>
   <groupId>com.example</groupId>
   <artifactId>module2</artifactId>
   <version>1.0</version>
   <type>jar</type>
   <scope>compile</scope>
</dependency>]
	at org.springframework.sbm.project.buildfile.OpenRewriteMavenBuildFileTest$GetDependenciesMultiModuleTest.getEffectiveDependencies(OpenRewriteMavenBuildFileTest.java:1031)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenRewriteMavenBuildFileTest$GetDependenciesMultiModuleTest.getEffectiveDependencies:1031 
Expected size: 3 but was: 2 in:
[<dependency>
   <groupId>javax.annotation</groupId>
   <artifactId>javax.annotation-api</artifactId>
   <version>1.3.2</version>
   <type>jar</type>
   <scope>test</scope>
</dependency>,
    <dependency>
   <groupId>com.example</groupId>
   <artifactId>module2</artifactId>
   <version>1.0</version>
   <type>jar</type>
   <scope>compile</scope>
</dependency>]
[INFO] 
[ERROR] Tests run: 291, Failures: 1, Errors: 0, Skipped: 1
[INFO] 

```

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [22.04]

**Additional context**

**Comment by bottemav** [comment]
If I print all dependencies of module1 in the failing test, then I have

* inside IntelliJ
```
{Compile=[com/example/module2/1.0/module2-1.0.pom,
    https://repo.maven.apache.org/maven2/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.pom],
Provided=[com/example/module2/1.0/module2-1.0.pom,
    https://repo.maven.apache.org/maven2/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.pom], 
Runtime=[com/example/module2/1.0/module2-1.0.pom,
    https://repo.maven.apache.org/maven2/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.pom], 
Test=[com/example/module2/1.0/module2-1.0.pom,
    ~\.m2\repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.pom,
    https://repo.maven.apache.org/maven2/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.pom]}
```
* on the command line
```
{Compile=[com/example/module2/1.0/module2-1.0.pom], 
Provided=[com/example/module2/1.0/module2-1.0.pom], 
Runtime=[com/example/module2/1.0/module2-1.0.pom], 
Test=[com/example/module2/1.0/module2-1.0.pom,
    ~\.m2\repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.pom]}

```

**Comment by abalzan** [comment]
After some analysis, it seems an issue with my local environment. Thanks for the support on this @bottemav 
Closing issue.
