### ISSUE TITLE
ERROR o.s.boot.SpringApplication - Application run failed

### ISSUE THREAD

**Issue by flashvayne** [spring-projects-experimental/spring-boot-migrator#742]
I have run the command 
```sh
java -jar --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED spring-boot-upgrade.jar demo-chatgpt-spring-boot-starter
```
 and then error occured as below. Scanned project is https://github.com/flashvayne/demo-chatgpt-spring-boot-starter.
+ JDK: openjdk version "17.0.6" 2023-01-17 LTS
+ OS: MacOS 13.2.1
```
Scanning demo-chatgpt-spring-boot-starter
20:31:32.926 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.sbm.engine.git.ProjectOutOfSyncException: It seems that the project was changed while running the recipe. The project was scanned again but you'll need to run the recipe again.
	at org.springframework.sbm.engine.git.ProjectSyncVerifier.verifyProjectIsInSyncWhenGitAvailable(ProjectSyncVerifier.java:57)
	at org.springframework.sbm.engine.commands.ApplyCommand.execute(ApplyCommand.java:64)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:46)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 common frames omitted
Failed to execute ApplicationRunner
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.sbm.engine.git.ProjectOutOfSyncException: It seems that the project was changed while running the recipe. The project was scanned again but you'll need to run the recipe again.
	at org.springframework.sbm.engine.git.ProjectSyncVerifier.verifyProjectIsInSyncWhenGitAvailable(ProjectSyncVerifier.java:57)
	at org.springframework.sbm.engine.commands.ApplyCommand.execute(ApplyCommand.java:64)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:46)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 more

```

**Comment by flashvayne** [comment]
I terminate the scanned project application and then it works.
So when the application is running, it can not be scanned.
