### ISSUE TITLE
NullPointerException when scanning the project:  Cannot read field "info" because "lintEnv" is null

### ISSUE THREAD

**Issue by juajuajuajuan** [spring-projects-experimental/spring-boot-migrator#757]
**Describe the bug**
When scanning the project, I get a NullPointer related to field "info" because of lintEnv being null. I'm not aware of that lintEnv even is.

**SBM Version**
Using v0.13.0

**SBM Application**
Tried both migrator and upgrade.

**To Reproduce**
1.- "java -jar spring-boot-migrator.jar" with java 17.0.2 (tried also 17.0.4).
2.- scan C:\\GitHome\\scouting\\scouting-be
3.- All 4 preconditions are greened ([ok]).
4.- Get the following output:
 Maven        100% │██████████████████████████████████│ 2/2 (0:00:09 / 0:00:00)
This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.

**Expected behavior**
Expected to see the recipes for upgrading from spring 2.7.10 to spring 3

**Stacktrace**
17:03:30.631 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
        at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:193)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:149)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:44)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 13 common frames omitted
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
        ... 23 common frames omitted
Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5340)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5200)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5145)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
        ... 22 common frames omitted
Failed to execute ApplicationRunner
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
        at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:193)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:149)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:44)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 13 more
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
        ... 23 more
Caused by: java.lang.NullPointerException: Cannot read field "info" because "lintEnv" is null
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5340)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5200)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5145)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
        ... 22 more

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 22H2

**Edit**
Edited to paste a longer stacktrace

**Comment by fabapp2** [comment]
Hi @juajuajuajuan
thanks for reporting 🚀 
Please delete/move your local m2 (`~/.m2/repository`) so no dependencies exist and try again. 
This will download dependencies again and hopefully, they're all good then and the error is gone.
Closing this issue, please reopen it in case the error persists.
