### ISSUE TITLE
Fail parseInputsToCompilerAst

### ISSUE THREAD

**Issue by JoeCqupt** [spring-projects-experimental/spring-boot-migrator#781]
**Describe the bug**
```
migrator:> scan /Users/*****/open/spring-boot-migrator/demos/spring-boot-3-upgrade-demo/demo-spring-song-app

scanning '/Users/*****/open/spring-boot-migrator/demos/spring-boot-3-upgrade-demo/demo-spring-song-app'

Checked preconditions for '/Users/*****/open/spring-boot-migrator/demos/spring-boot-3-upgrade-demo/demo-spring-song-app'
[ok] Found pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'false', Nothing will be committed.
[ok] Found required source dir 'src/main/java'.
[ok] Required Java version (17) was found.


Maven        100% │██████████████████████████████████│ 2/2 (0:00:03 / 0:00:00) 
This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.

migrator:> stacktrace
java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
	at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
	at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:38)
	at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
	at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:222)
	at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:115)
	at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
	at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
	at org.springframework.sbm.shell.ScanShellCommand.scan(ScanShellCommand.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.shell.command.invocation.InvocableShellMethod.doInvoke(InvocableShellMethod.java:306)
	at org.springframework.shell.command.invocation.InvocableShellMethod.invoke(InvocableShellMethod.java:232)
	at org.springframework.shell.command.CommandExecution$DefaultCommandExecution.evaluate(CommandExecution.java:158)
	at org.springframework.shell.Shell.evaluate(Shell.java:208)
	at org.springframework.shell.Shell.run(Shell.java:140)
	at org.springframework.shell.jline.InteractiveShellRunner.run(InteractiveShellRunner.java:73)
	at org.springframework.shell.DefaultShellApplicationRunner.run(DefaultShellApplicationRunner.java:65)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringShellApplication.main(SpringShellApplication.java:27)
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
	... 26 more
Caused by: java.lang.NullPointerException: Cannot read field "tsym" because "imp.qualid.selected.type" is null
	at com.sun.tools.javac.comp.Check.checkImportedPackagesObservable(Check.java:4020)
	at com.sun.tools.javac.comp.TypeEnter.finishImports(TypeEnter.java:229)
	at com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:214)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1410)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:610)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:587)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.enterAll(ReloadableJava17Parser.java:338)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:257)
	... 25 more
```

**SBM Version**

***main branch*** 
commitId:  8c0e880e0f140d864124fbafd86902066bcf1425

**SBM Application**
shell

**To Reproduce**

1. git checkout 
***main branch*** 
commitId:  8c0e880e0f140d864124fbafd86902066bcf1425

2. download  `spring-boot-3-upgrade-demo/demo-spring-song-app`

3. run `SpringShellApplication`

4. scan  path of `spring-boot-3-upgrade-demo/demo-spring-song-app`

**Expected behavior**

scan success

**Screenshots**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12369652/235092523-9e79c4ec-b535-42a0-a4b9-dcabf726bbd1.png">

**Stacktrace**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12369652/235092893-884f6731-da3f-49b7-9faa-4c2613ce3bb8.png">

**Desktop (please complete the following information):**
```
Darwin MacintoshdeMacBook-Pro-2.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
```

**Additional context**
none

**Comment by JoeCqupt** [comment]
project `demo-spring-song-app' ` was updated  accidentally
