### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KhalefAhmed** [spring-projects-experimental/spring-boot-migrator#795]
**Describe the bug**
 I had this bug and the application was not opened with an ide
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.sbm.engine.git.ProjectOutOfSyncException: It seems that the project was changed while running the recipe. The project was scanned again but you'll need to run the recipe again.
	at org.springframework.sbm.engine.git.ProjectSyncVerifier.verifyProjectIsInSyncWhenGitAvailable(ProjectSyncVerifier.java:57)
	at org.springframework.sbm.engine.commands.ApplyCommand.execute(ApplyCommand.java:64)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:46)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 common frames omitted
Failed to execute ApplicationRunner
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.sbm.engine.git.ProjectOutOfSyncException: It seems that the project was changed while running the recipe. The project was scanned again but you'll need to run the recipe again.
	at org.springframework.sbm.engine.git.ProjectSyncVerifier.verifyProjectIsInSyncWhenGitAvailable(ProjectSyncVerifier.java:57)
	at org.springframework.sbm.engine.commands.ApplyCommand.execute(ApplyCommand.java:64)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:46)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 more
**SBM Version**
i used the [0.13.0] version
**SBM Application**
Provide the application that was used. (shell, boot-upgrade, ...)
i used it in  iterm2

**Desktop (please complete the following information):**
 - OS: [mac] ventura 13.3.1

**Comment by bmaranan75** [comment]
Im getting the same exact error when trying to run upgrade report. is there any update on this?

**Comment by fabapp2** [comment]
Hi, I don't have time to look into this right now. 
As a workaround, could you try to pass `--sbm.gitSupportEnabled=false` on application startup to disable these checks.

**Comment by abine-ryan-brumm** [comment]
Any update? I'm getting this same issue
