### ISSUE TITLE
Failed to execute ApplicationRunner while scanning an application 

### ISSUE THREAD

**Issue by atanasg** [spring-projects-experimental/spring-boot-migrator#801]
**Describe the bug**
Executing ```java -jar --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED spring-boot-upgrade.jar <our_app_folder>``` ends after some minutes with an exception.

**SBM Version**
Downloaded https://github.com/spring-projects-experimental/spring-boot-migrator/releases/latest/download/spring-boot-upgrade.jar, should be 0.13.0

**SBM Application**
boot-upgrade

**To Reproduce**
We have a medium-sized REST application already migrated to Java 17 and spring-boot 3.1.0. We wanted to still run the upgrade tool to see if it recommends some further changes in our code related to Spring Boot 3.

**Expected behavior**
Scan finishes successfully. Some report is generated and is accessible in the browser.

**Screenshots**

**Stacktrace**
```
Scanning C:\Development\<app>
21:54:05.593 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
        at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:193)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:149)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:44)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 13 common frames omitted
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
        ... 23 common frames omitted
Caused by: java.lang.AssertionError: null
        at com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
        at com.sun.tools.javac.util.ListBuffer.append(ListBuffer.java:127)
        at com.sun.tools.javac.comp.Attr$1.visitYield(Attr.java:1621)
        at com.sun.tools.javac.tree.JCTree$JCYield.accept(JCTree.java:1658)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at com.sun.tools.javac.comp.Attr.lambda$visitSwitchExpression$7(Attr.java:1628)
        at com.sun.tools.javac.comp.Attr.handleSwitch(Attr.java:1797)
        at com.sun.tools.javac.comp.Attr.visitSwitchExpression(Attr.java:1613)
        at com.sun.tools.javac.tree.JCTree$JCSwitchExpression.accept(JCTree.java:1380)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:2425)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1709)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
        at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.visitIf(Attr.java:2198)
        at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1553)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
        at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1238)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5462)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5353)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5184)
        at com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:980)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5462)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5353)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5184)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5142)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
        ... 22 common frames omitted
Failed to execute ApplicationRunner
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
        at org.springframework.sbm.openrewrite.RewriteExecutionContext.lambda$createErrorHandler$0(RewriteExecutionContext.java:58)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
        at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:43)
        at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:61)
        at org.springframework.sbm.project.parser.MavenProjectParser.parseTestJavaSources(MavenProjectParser.java:193)
        at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:149)
        at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:53)
        at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:57)
        at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:44)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
        ... 13 more
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
        ... 23 more
Caused by: java.lang.AssertionError
        at com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at com.sun.tools.javac.util.Assert.checkNonNull(Assert.java:62)
        at com.sun.tools.javac.util.ListBuffer.append(ListBuffer.java:127)
        at com.sun.tools.javac.comp.Attr$1.visitYield(Attr.java:1621)
        at com.sun.tools.javac.tree.JCTree$JCYield.accept(JCTree.java:1658)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
        at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
        at com.sun.tools.javac.comp.Attr.lambda$visitSwitchExpression$7(Attr.java:1628)
        at com.sun.tools.javac.comp.Attr.handleSwitch(Attr.java:1797)
        at com.sun.tools.javac.comp.Attr.visitSwitchExpression(Attr.java:1613)
        at com.sun.tools.javac.tree.JCTree$JCSwitchExpression.accept(JCTree.java:1380)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:2425)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1709)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
        at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.visitIf(Attr.java:2198)
        at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1553)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:770)
        at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1448)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1238)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5462)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5353)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5184)
        at com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:980)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:677)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:751)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5462)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5353)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5184)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:5142)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1290)
        at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:266)
        ... 22 more
```

**Example Source code to replicate the issue (Optional)**
It would help us immensely if we were to have an example test source code or a snippet where you can see this problem, you could attach a zip file along with this issue. 

Although this section is optional, it would speed up our process of providing a fix. 
P.S. Please remove any sensitive data and do not upload any proprietary source.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by fabapp2** [comment]
Hi @atanasg 
aplogies for my late reply. 
The stacktrace lat's me think there's a broken jar. 
This was often the case with 0.13.0. In 0.14.0 this didn't change.
Please activate logging to find out which jar it is. 
Or, brute force, rename `./m2/repository` and run again to trigger a new download of the jars.
I'll close the issue hoping this resolves it. Feel free to reopen otherwise.
