### ISSUE TITLE
`Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null`

### ISSUE THREAD

**Issue by fzyzcjy** [spring-projects-experimental/spring-boot-migrator#848]
**Describe the bug**
Hi thanks for the tool! However it errors as follows.

I am using kotlin in spring boot, can that be problem?

```
(base) ➜  temp java -jar --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED ~/Downloads/spring-boot-upgrade.jar /Users/tom/Main/yplusplus/backend/app/

 _____            _              ______             _     _____
/  ___|          (_)             | ___ \           | |   |____ |
\ `--. _ __  _ __ _ _ __   __ _  | |_/ / ___   ___ | |_      / /
 `--. \ '_ \| '__| | '_ \ / _` | | ___ \/ _ \ / _ \| __|     \ \
/\__/ / |_) | |  | | | | | (_| | | |_/ / (_) | (_) | |_  .___/ /
\____/| .__/|_|  |_|_| |_|\__, | \____/ \___/ \___/ \__| \____/
      | |                  __/ |
      |_|                 |___/
 _   _                           _       ______                      _
| | | |                         | |      | ___ \                    | |
| | | |_ __   __ _ _ __ __ _  __| | ___  | |_/ /___ _ __   ___  _ __| |_
| | | | '_ \ / _` | '__/ _` |/ _` |/ _ \ |    // _ \ '_ \ / _ \| '__| __|
| |_| | |_) | (_| | | | (_| | (_| |  __/ | |\ \  __/ |_) | (_) | |  | |_
 \___/| .__/ \__, |_|  \__,_|\__,_|\___| \_| \_\___| .__/ \___/|_|   \__|
      | |     __/ |                                | |
      |_|    |___/                                 |_|

powered by Spring Boot Migrator

-------------------------------------------------------------------------

Find us on GitHub:  https://via.vmw.com/8AD63p

Please report all errors:  https://via.vmw.com/bXlqJC

-------------------------------------------------------------------------

Scanning /Users/tom/Main/yplusplus/backend/app/
09:02:45.971 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
	at org.springframework.sbm.openrewrite.RewriteExecutionContextErrorHandler.accept(RewriteExecutionContextErrorHandler.java:44)
	at org.springframework.sbm.openrewrite.RewriteExecutionContextErrorHandler.accept(RewriteExecutionContextErrorHandler.java:27)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
	at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:38)
	at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:64)
	at org.springframework.sbm.java.impl.RewriteJavaParser$$FastClassBySpringCGLIB$$93b26c14.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.springframework.sbm.java.impl.RewriteJavaParser$$EnhancerBySpringCGLIB$$9ea8b4cb.parseInputs(<generated>)
	at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:233)
	at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:124)
	at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:52)
	at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:70)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:48)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 common frames omitted
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
	... 34 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null
	at com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:172)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:627)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:587)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.enterAll(ReloadableJava17Parser.java:338)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:257)
	... 33 common frames omitted
Failed to execute ApplicationRunner
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: This could be a broken jar. Activate logging on WARN level for 'org.openrewrite' might reveal more information.
	at org.springframework.sbm.openrewrite.RewriteExecutionContextErrorHandler.accept(RewriteExecutionContextErrorHandler.java:44)
	at org.springframework.sbm.openrewrite.RewriteExecutionContextErrorHandler.accept(RewriteExecutionContextErrorHandler.java:27)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:270)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputs(ReloadableJava17Parser.java:161)
	at org.openrewrite.java.Java17Parser.parseInputs(Java17Parser.java:38)
	at org.springframework.sbm.java.impl.RewriteJavaParser.parseInputs(RewriteJavaParser.java:64)
	at org.springframework.sbm.java.impl.RewriteJavaParser$$FastClassBySpringCGLIB$$93b26c14.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.springframework.sbm.java.impl.RewriteJavaParser$$EnhancerBySpringCGLIB$$9ea8b4cb.parseInputs(<generated>)
	at org.springframework.sbm.project.parser.MavenProjectParser.parseMainJavaSources(MavenProjectParser.java:233)
	at org.springframework.sbm.project.parser.MavenProjectParser.parse(MavenProjectParser.java:124)
	at org.springframework.sbm.project.parser.ProjectContextInitializer.initProjectContext(ProjectContextInitializer.java:52)
	at org.springframework.sbm.engine.commands.ScanCommand.execute(ScanCommand.java:70)
	at org.springframework.sbm.SpringBootMigratorRunner.run(SpringBootMigratorRunner.java:48)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	... 13 more
Caused by: org.openrewrite.java.JavaParsingException: Failed symbol entering or attribution
	... 34 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null
	at com.sun.tools.javac.comp.TypeEnter.ensureImportsChecked(TypeEnter.java:172)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:627)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:587)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.enterAll(ReloadableJava17Parser.java:338)
	at org.openrewrite.java.isolated.ReloadableJava17Parser.parseInputsToCompilerAst(ReloadableJava17Parser.java:257)
	... 33 more
(base) ➜  temp 
```

**SBM Version**
latest

**SBM Application**
command line

**To Reproduce**

**Expected behavior**
no err

**Screenshots**

**Stacktrace**
see above

**Example Source code to replicate the issue (Optional)**
It would help us immensely if we were to have an example test source code or a snippet where you can see this problem, you could attach a zip file along with this issue. 

Although this section is optional, it would speed up our process of providing a fix. 
P.S. Please remove any sensitive data and do not upload any proprietary source.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by fabapp2** [comment]
Hi @fzyzcjy 
thanks for reporting and giving SBM a try. 
Unfortunately you're right. Kotlin is not supported at the moment. I'll close the issue.

**Comment by fzyzcjy** [comment]
@fabapp2 Hi thank you for the reply! Looking forward to kotlin support

**Comment by fabapp2** [comment]
We're reworking the Parser and Gradle support will cone with it. I will see what it takes to provide access to OpenRewrite's Kotlin support too.
