### ISSUE TITLE
Problems resolving Maven with Windows

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#922]
Interesting. I will look into it. 

_Originally posted by @fabapp2 in https://github.com/spring-projects-experimental/spring-boot-migrator/issues/867#issuecomment-1715749455_

**Comment by kurkov** [comment]
Hi @fabapp2 
I have similar issue. 
Tried both `spring-boot-migrator.jar` and `spring-boot-upgrade.jar`

I got this error:
```
14:05:29.561 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at org.springframework.sbm.SpringBootUpgradeReportApp.main(SpringBootUpgradeReportApp.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 7: file://D:\Users\kurkov\.m2\repository/company/eip-spring-boot-parent/4.0.0/eip-spring-boot-parent-4.0.0.pom

```
Is there a solution for this issue, or should I just wait for a new release?
